quiz/urls.py
from django.conf.urls.defaults import *

urlpatterns = patterns('',
	url(r'^(?P<slug>[-\w]+)/process/$',
		view	= 'quiz.views.process_quiz',
		name	= 'process_quiz',
	),
	url(r'^(?P<slug>[-\w]+)/$',
		view	= 'quiz.views.quiz_detail',
		name	= 'quiz_detail',
	),
	url(r'^$',
		view	= 'quiz.views.quiz_dashboard',
		name	= 'quiz_dashboard',
	)
)

resale_cert/urls.py
from django.conf.urls import patterns, url

from resale_cert import views

urlpatterns = patterns('',
    url(r'^$', views.index, name='index'),

)

utilities/urls.py
from django.conf.urls import patterns, include, url
from django.views.generic.base import RedirectView
#from django.conf.urls.defaults import *
import settings

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()



urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'utilities.views.home', name='home'),
    # url(r'^utilities/', include('utilities.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
    
    #custom admin view
    url(r'^admin/tutorials/tutorials/$', 'tutorials.views.tutorials_view'),
    
    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
    
    url(r'^$', 'utilities.views.home'),
    url(r'^supply/', include('supply.urls', namespace="supply")),
    url(r'^tracking/', include('tracking.urls', namespace="tracking")),
    url(r'^shipping/', include('shipping.urls', namespace="shipping")),
    url(r'^freightsolution/', include('freightsolution.urls', namespace="freight")),
    url(r'^resale_cert/', include('resale_cert.urls', namespace="resale_cert")),
    url(r'^chat/', include('djangoChat.urls')),
    
    #url(r'^media/', 'django.views.static.serve',{'document_root': settings.MEDIA_ROOT})
    url(r'^favicon\.ico$', RedirectView.as_view(url='shopmro.com/utilities/favicon.ico')),

)

resale_cert/models.py
from django.db import models
from django import forms
import datetime

# Create your models here.

class Reseller(models.Model):
    permit_number = models.CharField(max_length=50)
    validation = models.CharField(max_length=20)
    owner = models.CharField(max_length=100)
    bussiness_name = models.CharField(max_length=100)
    address = models.CharField(max_length=100)
    city = models.CharField(max_length=50)
    state = models.CharField(max_length=5)
    start_date = models.DateField(default=datetime.date.today, blank=True)

    def __unicode__(self):
        return self.validation

    def write_output(self, dictionary):
        if type(dictionary) is dict:
            try:
                Reseller.objects.get(permit_number=dictionary['permit_no'])
            except Reseller.DoesNotExist:
                reseller = Reseller()
                reseller.permit_number = dictionary['permit_no']
                reseller.validation = dictionary['valid']
                reseller.owner = dictionary['owner']
                reseller.business_name = dictionary['bussiness_name']
                reseller.address = dictionary['address']
                reseller.city = dictionary['city']
                reseller.state = dictionary['state']
                if dictionary['start_date']:
                    reseller.start_date = dictionary['start_date']
                reseller.save()
            else:
                pass


class InputForm(forms.Form):
    permit_number = forms.IntegerField()

resale_cert/views.py
# Create your views here.
# Create your views here.
# from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from django.core.context_processors import csrf
from datetime import datetime
from resale_cert.models import InputForm, Reseller
from scrapper.efile import EfileScraper


def index(request):
    if request.method == 'POST':
        form = InputForm(request.POST)
        # return HttpResponse(form.cleaned_data)
        if form.is_valid():
            permit_number = form.cleaned_data['permit_number']
            scraper = EfileScraper()
            output = scraper.get_permit(permit_number)
            reseller = Reseller()
            reseller.write_output(output)

            context = {'owner': output['owner'], 'status':output['valid']}
            return render(request, 'resale_cert/index.html', context)

        else:
            context = {'info': 'The data introduced is not valid.'}
            return render(request, 'resale_cert/index.html', context)
    else:
        form = InputForm()
        context = {'results': ''}
        return render(request, 'resale_cert/index.html', context)

resale_cert/templates/resale_cert/index.html
<head>
	<title>Resellers Check</title>
	<link rel="stylesheet" type="text/css" href="{{ STATIC_URL }}resale_cert/style.css">
	
</head>
<script>
	function clearBox(){
		document.getElementById("permit_number").value = '';
	}

	
	function isNumber(n) {
	  return !isNaN(parseFloat(n)) && isFinite(n);
	}
	
	function validateForm(){
		var permit_number=document.forms["resaleForm"]["permit_number"].value;
		if (!isNumber(permit_number)) {
			alert('Enter the numeric portion only. Omit letters and other symbols (e.g. dashes.)');
			return false;
		}
		
	}
	
	
		
	
	
</script>

<body onload="inputDate()">
<div class="container">
{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}


<form action="{% url 'resale_cert:index' %}" method="post" class="inputForm" name="resaleForm" onsubmit="return validateForm();" >
	{% csrf_token %}
	<h4 class="subtitle">Resale Cert:</h4>
	<div class="button_container">
	<input type="button" class="button" value="Clear" title="Clear the contents of the input box." onclick="clearBox()"/>
	</div>
	<div class="inputsContainer">
	<label class="label_input">Permit Number:</label>
	<input class="inputclass" name="permit_number" id="permit_number" value="{{permit_number}}" title="Enter the numeric portion only. Omit letters and other symbols (e.g. dashes.)"/>
	</div>
	<div class="button_container">
	<input type="submit" class="button" value="Search" title="Search the selected supplier." />
	</div>
</form>

<div class="resultTable">
	{% if status %}
	{% if status == "Valid" %}
		<h4 class="green">{{ status|safe }}</h4>
	{% else %}
		<h4 class="red">{{ status|safe }}</h4>
	{% endif %}
	{% if status %}
	<label>Owner:</label>
	<span>{{owner|safe}}</span>
	{% endif %}
	{% endif %}
</div>
</div>
</body>