quiz/urls.py
from django.conf.urls.defaults import *

urlpatterns = patterns('',
	url(r'^(?P<slug>[-\w]+)/process/$',
		view	= 'quiz.views.process_quiz',
		name	= 'process_quiz',
	),
	url(r'^(?P<slug>[-\w]+)/$',
		view	= 'quiz.views.quiz_detail',
		name	= 'quiz_detail',
	),
	url(r'^$',
		view	= 'quiz.views.quiz_dashboard',
		name	= 'quiz_dashboard',
	)
)

tracking/urls.py
from django.conf.urls import patterns, url

from tracking import views

urlpatterns = patterns('',
    url(r'^$', views.index, name='index'),

)

utilities/urls.py
from django.conf.urls import patterns, include, url
from django.views.generic.base import RedirectView
#from django.conf.urls.defaults import *
import settings

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()



urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'utilities.views.home', name='home'),
    # url(r'^utilities/', include('utilities.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
    
    #custom admin view
    url(r'^admin/tutorials/tutorials/$', 'tutorials.views.tutorials_view'),
    
    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
    
    url(r'^$', 'utilities.views.home'),
    url(r'^supply/', include('supply.urls', namespace="supply")),
    url(r'^tracking/', include('tracking.urls', namespace="tracking")),
    url(r'^shipping/', include('shipping.urls', namespace="shipping")),
    url(r'^freightsolution/', include('freightsolution.urls', namespace="freight")),
    url(r'^resale_cert/', include('resale_cert.urls', namespace="resale_cert")),
    url(r'^chat/', include('djangoChat.urls')),
    
    #url(r'^media/', 'django.views.static.serve',{'document_root': settings.MEDIA_ROOT})
    url(r'^favicon\.ico$', RedirectView.as_view(url='shopmro.com/utilities/favicon.ico')),

)

tracking/models.py
from django.db import models
from django import forms

# Create your models here.

class Shipping(models.Model):
    orderNumber = models.CharField(max_length=50)
    trackNumber = models.CharField(max_length=50)
    company = models.CharField(max_length=100)
    dateAdded = models.DateTimeField('date introduced')
    
    def __unicode__(self):
        return self.orderNumber
    
    def bostonGear(self):
        pass
    
    def baldorVip(self):
        pass
    

class InputForm(forms.Form):
    codes = forms.CharField(max_length=100)
    company = forms.CharField(max_length=100)

tracking/views.py
# Create your views here.
# from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from django.core.context_processors import csrf
import baldorVip
import bostonGear
import martinSprocket
import json
from scripts.baldor import BaldorScraper
# from scripts.bando import BandoScraper
from scripts.boston import BostonScraper
from scripts.dodge import DodgeScraper
from scripts.gates import GatesScraper
from scripts.leeson import LeesonScraper
from scripts.martin import MartinScraper
from scripts.maska import MaskaScraper
from scripts.mrc import MrcScraper
# from scripts.nachi import NachiScraper
# from scripts.nexen import NexenScraper
from scripts.redlion import RedlionScraper
from scripts.weg import WegScraper

from tracking.models import Shipping, InputForm

def index(request):
    if request.method == 'POST':
        form = InputForm(request.POST)
        # return HttpResponse(form.cleaned_data)
        if form.is_valid():
            codes = form.cleaned_data['codes'].split('\r\n')
            company = form.cleaned_data['company']
            if company == 'BaldorVip':
                tracking_numbers = baldorVip.search_codes(codes)
            elif company == 'BostonGear':
                tracking_numbers = bostonGear.search_codes(codes)
            elif company == 'MartinSp':
                tracking_numbers = martinSprocket.search_codes(codes)
            else:
                name = company[0].upper() + company[1:]
                scraper = eval(name + 'Scraper()')
                tracking_numbers = []
                for code in codes:
                    if code == '':
                        continue
                    track_number = scraper.get_tracking(code)
                    tracking_numbers.append(track_number)

            tracking_numbers = '\r\n'.join(tracking_numbers)
            codes = '\r\n'.join(codes)
            context = {'codes':codes, 'company': company, 'tracking': tracking_numbers, 'info':'Done. These are all the results.'}
            return render(request, 'tracking/index.html', context)

        else:
            context = {'info': 'You didn\'t introduced any data.'}
            return render(request, 'tracking/index.html', context)
    else:
        form = InputForm()
        context = {'tracking': ''}
        return render(request, 'tracking/index.html', context)

tracking/templates/tracking/detail.html
<h1>Please paste here the order codes you want to check:</h1>
<h1>{{ shipping.orderNumber }}</h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'tracking:check' shipping.orderNumber %}" method="post">
{% csrf_token %}
{% for choice in poll.choice_set.all %}
    <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}" />
    <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br />
{% endfor %}
<input type="submit" value="Vote" />
</form>

tracking/templates/tracking/index.html
<head>
	<title>Check Shipping Status</title>
	<link rel="stylesheet" type="text/css" href="{{ STATIC_URL }}tracking/style.css">
	
</head>
<script>
	function message(message){
		document.getElementById('message').innerHTML = message;
	}
	
	function clearBox(){
		document.getElementById("orderNumbers").innerHTML = '';
                document.getElementById('orderNumbers').value = '';
	}
	
		
</script>


<div class="container">
<h4 id="message" class="instructions">{{info}}</h4>
{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'tracking:index' %}" method="post" class="inputForm">
	{% csrf_token %}
	<h4 class="subtitle">Order Numbers</h4>
	<div class="controls">
	<input type="button" class="button" value="Clear" title="Clear the contents of the input box." onclick="clearBox()"/>
	</div>
	<textarea class="textArea" rows="25" cols="20" name="codes" id="orderNumbers" title="Please paste here the order codes you want to check.">{{ codes }}</textarea>
	<div class="controls">
	<div class="button_container">
	<input type="radio" class="radio" value="BaldorVip" name="company" id="BaldorVip" checked="checked"/>
	<label class="label_radio">Baldor</label>
	</div>
	<div class="button_container">
	<input type="radio" class="radio" value="BostonGear" name="company" id="BostonGear"/>
	<label class="label_radio">BostonGear</label>
	</div>
	<div class="button_container last">
	<input type="radio" class="radio" value="BaldorVip" name="company" id="Maska"/>
	<label class="label_radio">Maska</label>
	</div>
	<div class="button_container">
	<input type="radio" class="radio" value="leeson" name="company" id="Leeson"/>
	<label class="label_radio">Leeson</label>
	</div>
	<div class="button_container">
	<input type="radio" class="radio" value="leeson" name="company" id="Electra"/>
	<label class="label_radio">ElectraGear</label>
	</div>
	<div class="button_container last">
	<input type="radio" class="radio" value="mrc" name="company" id="Mrc"/>
	<label class="label_radio">MRC</label>
	</div>
	<div class="button_container">
	<input type="radio" class="radio" value="leeson" name="company" id="Lincoln"/>
	<label class="label_radio">Lincoln</label>
	</div>
	<div class="button_container">
	<input type="radio" class="radio" value="leeson" name="company" id="Grove"/>
	<label class="label_radio">GroveGear</label>
	</div>
	<div class="button_container last">
	<input type="radio" class="radio" value="dodge" name="company" id="Dodge"/>
	<label class="label_radio">Dodge</label>
	</div>
	<div class="button_container">
	<input type="radio" class="radio" value="weg" name="company" id="Weg"/>
	<label class="label_radio">WEG</label>
	</div>
	<div class="button_container">
	<input type="radio" class="radio" value="MartinSp" name="company" id="MartinSprocket"/>
	<label class="label_radio">MartinSpr</label>
	</div>
	<div class="button_container last">
	<input type="radio" class="radio" value="gates" name="company" id="Gates"/>
	<label class="label_radio">Gates</label>
	</div>
	<div class="button_container">
	<input type="radio" class="radio" value="redlion" name="company" id="Redlion"/>
	<label class="label_radio">Redlion</label>
	</div>
	
	
	
	
	
	
        </div>
        <div class="searchButton_container">
	<input type="submit" class="button" value="Search" title="Search the selected supplier." onclick="message('Working... Please wait a minute.')"/>
	</div>
</form>

<div class="inputForm">
	<h4 class="subtitle">Tracking Numbers</h4>
	<textarea class="textArea" id="trackingNumbers" rows="25" cols="20" readonly="readonly" title="The results will appear shortly here, exactly in the same order.">{{ tracking }}</textarea>
</div>
</div>

tracking/templates/tracking/index2.html
<head>
	<title>Check Shipping Status</title>
	<link rel="stylesheet" type="text/css" href="{{ STATIC_URL }}tracking/style.css">
	
</head>


<h3 class="instructions">Please paste here the order codes you want to check:</h3>
{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}


<form action="{% url 'tracking:search' %}" method="post" class="container">
{% csrf_token %}
<h4>Order Numbers</h4>
<input type="text" autofocus="autofocus" class="textBox" name="codes" id="orderNumbers" value="" autocomplete='off'>

<input type="radio" class="radio" value="BaldorVip" name="company" id="BaldorVip" checked="checked"/><label>BaldorVip</label>
<input type="radio" class="radio" value="BostonGear" name="company" id="BostonGear"/><label>BostonGear</label>

<input type="submit" class="button" value="Search" />
</form>



tracking/templates/tracking/search.html
<head>
<title>Tracking Numbers</title>
<link rel="stylesheet" type="text/css" href="{{ STATIC_URL }}tracking/style.css">
</head>

<body>
<div class="container">	
<h3 class="instructions">These are the tracking numbers from {{ company }} </h3>
<textarea class="textArea" rows="25" cols="20" readonly="readonly">{{ codes }}</textarea>
<textarea class="textArea" rows="25" cols="20" readonly="readonly">{{ tracking }}</textarea>

{% if latest_numbers %}
    <ul>
    {% for shipping in latest_numbers %}
        <li><a href="/tracking/{{ shipping.orderNumber }}/">{{ shipping.trackNumber }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No recent order numbers were introduced.</p>
{% endif %}

</div>

</body>