quiz/urls.py
from django.conf.urls.defaults import *

urlpatterns = patterns('',
	url(r'^(?P<slug>[-\w]+)/process/$',
		view	= 'quiz.views.process_quiz',
		name	= 'process_quiz',
	),
	url(r'^(?P<slug>[-\w]+)/$',
		view	= 'quiz.views.quiz_detail',
		name	= 'quiz_detail',
	),
	url(r'^$',
		view	= 'quiz.views.quiz_dashboard',
		name	= 'quiz_dashboard',
	)
)

shipping/urls.py
from django.conf.urls import patterns, url

from shipping import views

urlpatterns = patterns('',
    url(r'^$', views.index, name='index'),
    url(r'^estimate/$', views.estimate, name='estimate'),
    url(r'^international/$', views.international, name='international'),
)

utilities/urls.py
from django.conf.urls import patterns, include, url
from django.views.generic.base import RedirectView
#from django.conf.urls.defaults import *
import settings

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()



urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'utilities.views.home', name='home'),
    # url(r'^utilities/', include('utilities.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
    
    #custom admin view
    url(r'^admin/tutorials/tutorials/$', 'tutorials.views.tutorials_view'),
    
    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
    
    url(r'^$', 'utilities.views.home'),
    url(r'^supply/', include('supply.urls', namespace="supply")),
    url(r'^tracking/', include('tracking.urls', namespace="tracking")),
    url(r'^shipping/', include('shipping.urls', namespace="shipping")),
    url(r'^freightsolution/', include('freightsolution.urls', namespace="freight")),
    url(r'^resale_cert/', include('resale_cert.urls', namespace="resale_cert")),
    url(r'^chat/', include('djangoChat.urls')),
    
    #url(r'^media/', 'django.views.static.serve',{'document_root': settings.MEDIA_ROOT})
    url(r'^favicon\.ico$', RedirectView.as_view(url='shopmro.com/utilities/favicon.ico')),

)

shipping/models.py
from django.db import models
from django import forms

# Create your models here.

class Shipping(models.Model):
    zipcode1 = models.PositiveIntegerField()
    zipcode2 = models.PositiveIntegerField()
    weight = models.PositiveIntegerField()
    # part_number = models.CharField(max_length=50)
    date1 = models.DateField()
    carrier = models.CharField(max_length=50)


class InputForm(forms.Form):
    zipcode1 = forms.IntegerField()
    zipcode2 = forms.IntegerField()
    weight = forms.IntegerField()
    # part_number = forms.CharField(max_length=50)
    date1 = forms.DateField()
    carrier = forms.CharField(max_length=50)


class InternationalForm(forms.Form):
    zipcode1 = forms.CharField()
    zipcode2 = forms.CharField()
    from_country = forms.CharField()
    to_country = forms.CharField()
    weight = forms.FloatField()
    carrier = forms.CharField(max_length=50)

shipping/views.py
# Create your views here.
# Create your views here.
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from django.core.context_processors import csrf
from datetime import datetime
import json

from shipping.models import InputForm, InternationalForm
from UPS_scraper import UpsScraper
from IdcUsa import IdcScraper
from ups.client import UPSClient
from ups.model import Address, Package
from dhl.client import DHLClient


def index(request):
    if request.method == 'POST':
        form = InputForm(request.POST)
        # return HttpResponse(form.cleaned_data)
        if form.is_valid():
            zipcode1 = form.cleaned_data['zipcode1']
            zipcode2 = form.cleaned_data['zipcode2']
            weight = form.cleaned_data['weight']
            date1 = form.cleaned_data['date1']
            carrier = form.cleaned_data['carrier']
            if carrier == 'UPS':
                scraper = UpsScraper()
                # print scraper.get_availability('AEM2238-4')
                results = scraper.get_estimate(zipcode1, zipcode2, weight, date1)
                if results == '':
                    context = {'info': 'The UPS website is down. Please try again later.'}
                    return render(request, 'shipping/index.html', context)

            if carrier == 'IDC':
                #scraper = IdcScraper()
                #results = scraper.get_estimate(zipcode1, zipcode2, weight)
                context = {'info': 'The IDC_USA service is not available.'}
                return render(request, 'shipping/index.html', context)

            context = {'results':results, 'info':'Done. These are all the results.', 'zipcode1':zipcode1, 'zipcode2':zipcode2, 'weight':weight, 'date1':date1.strftime('%m/%d/%Y')}
            return render(request, 'shipping/index.html', context)

        else:
            context = {'info': 'The data introduced is not valid.'}
            return render(request, 'shipping/index.html', context)
    else:
        form = InputForm()
        context = {'results': ''}
        return render(request, 'shipping/index.html', context)


def estimate(request):
    today = datetime.today()
    # date = today.strftime('%m/%d/%Y')
    if request.method == 'GET':
        zipcode1 = request.GET.get('zipcode1', '')
        zipcode2 = request.GET.get('zipcode2', '')
        weight = request.GET.get('weight', 0)
        if float(weight) == 0:
            weight = 0.9
            
        if float(weight) > 150:
            scraper = UpsScraper()
            ups_result = scraper.get_freight_estimate(zipcode1, zipcode2, weight)
            scraper = IdcScraper()
            idc_result = scraper.get_freight(zipcode1, zipcode2, weight, today)
            output = 'UPS Next Day Air:<br>$%s<br>FedEx Freight:<br>$%s' %(ups_result, idc_result)
        else:
            scraper = UpsScraper()
            ups_result = scraper.get_ups_ground(zipcode1, zipcode2, weight, today)
            scraper = IdcScraper()
            idc_result = scraper.get_freight(zipcode1, zipcode2, weight, today)
            output = 'UPS Ground:<br>$%s<br>FedEx Freight:<br>$%s' %(ups_result, idc_result)
        return HttpResponse(output)



def international(request):
    mro_credentials = { 'username': 'mrosupply_ups',
                        'password': '1o8c9r8al!@#$',
                        'access_license': '6CC3FBEBBDC01626',
                        'shipper_number': '929702'
                        }
    if request.method == 'POST':
        form = InternationalForm(request.POST)
        #return HttpResponse(form.is_valid())
        if form.is_valid():
            from_zipcode = form.cleaned_data['zipcode1']
            to_zipcode = form.cleaned_data['zipcode2']
            from_country = form.cleaned_data['from_country']
            to_country = form.cleaned_data['to_country']
            weight = form.cleaned_data['weight']
            carrier = form.cleaned_data['carrier']
            
            package = [Package(weight)]
            from_address = Address(zip=from_zipcode, country=from_country)
            to_address = Address(zip=to_zipcode, country=to_country)
            
            
            if carrier == 'UPS':
                ups = UPSClient(mro_credentials)
                response = ups.rate(packages=package, packaging_type='02',
                                 shipper=from_address, recipient=to_address)
                content = response["info"]
            else:
                dhl = DHLClient()
                response = dhl.rate(packages=package, shipper=from_address,
                                     recipient=to_address)
                content = response["info"]
            table = "<table><thead><tr><th>Service</th><th>Price</th></tr></thead><tbody>"
            for result in content:
                shipping_method = result["service"]
                price = result["total_cost"]
                table += "<tr><td>%s</td><td>%s</td></tr>" %(shipping_method, price)
            table += "</tbody></table>" 
            context = {'results':table, 'info':'Done. These are all the results.', 'zipcode1':from_zipcode, 'zipcode2':to_zipcode,
                        'weight':weight}
            return render(request, 'shipping/international.html', context)

        else:
            context = {'info': 'The data introduced is not valid.'}
            return render(request, 'shipping/international.html', context)
    else:
        form = InputForm()
        context = {'results': ''}
        return render(request, 'shipping/international.html', context)
    
    

shipping/templates/shipping/detail.html
<h1>Please paste here the order codes you want to check:</h1>
<h1>{{ shipping.orderNumber }}</h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'tracking:check' shipping.orderNumber %}" method="post">
{% csrf_token %}
{% for choice in poll.choice_set.all %}
    <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}" />
    <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br />
{% endfor %}
<input type="submit" value="Vote" />
</form>

shipping/templates/shipping/index.html
<head>
	<title>Shipping Cost Calculator</title>
	<link rel="stylesheet" type="text/css" href="{{ STATIC_URL }}shipping/style.css">
	
</head>
<script>
	function message(message){
		document.getElementById('message').innerHTML = message;
	}
	
	function clearBox(){
		document.getElementById("zipcode1").value = '';
		document.getElementById("zipcode2").value = '';
		document.getElementById("weight").value = '';
	}
	
	function focusInBox(){
		var today = new Date();
		var dd = today.getDate();
		var mm = today.getMonth()+1; //January is 0!
		var yyyy = today.getFullYear();
		if(dd<10){dd='0'+dd} {if(mm<10){mm='0'+mm} today = mm+'/'+dd+'/'+yyyy;}
		var box = document.getElementById("date1");
		if (box.value==today) {
			box.value = '';
		}
	}

	function focusOutBox(){
		var today = new Date();
		var dd = today.getDate();
		var mm = today.getMonth()+1; //January is 0!
		var yyyy = today.getFullYear();
		if(dd<10){dd='0'+dd} {if(mm<10){mm='0'+mm} today = mm+'/'+dd+'/'+yyyy;}
		var box = document.getElementById("date1");
		if (box.value=="") {
			box.value = today;
		}
	}
		
	function warehouse(obj) {
        var input_elem = document.getElementById("zipcode1");
        switch (obj.selectedIndex) {
		  case 0:
		    input_elem.value = '90023';
		    break;
		  case 1:
		    input_elem.value = '01569';
		    break;
		  case 2:
		    input_elem.value = '38555';
		    break;
		  case 3:
		    input_elem.value = '53182';
		    break;
		  case 4:
		    input_elem.value = '46242';
		    break;
		  case 5:
		    input_elem.value = '17402';
		    break;
		  case 6:
		    input_elem.value = '28216';
		    break;
		  case 7:
		    input_elem.value = '89502';
		    break;
		  case 8:
		    input_elem.value = '55344';
		    break;              		    
		  case 9:
		    input_elem.value = '73114';
		    break;
		  default:
		    input_elem.value = '';
		    break;
		}
	
	}
	
	function inputDate(){
		var today = new Date();
		var dd = today.getDate();
		var mm = today.getMonth()+1; //January is 0!
		
		var yyyy = today.getFullYear();
		if(dd<10){dd='0'+dd} {if(mm<10){mm='0'+mm} today = mm+'/'+dd+'/'+yyyy;}
		document.getElementById("date1").value = today;
	}
	
	function isNumber(n) {
	  return !isNaN(parseFloat(n)) && isFinite(n);
	}
	
	function validateForm(){
		var zipcode1=document.forms["shippingForm"]["zipcode1"].value;
		var zipcode2=document.forms["shippingForm"]["zipcode2"].value;
		var weight=document.forms["shippingForm"]["weight"].value;
		var date1=document.forms["shippingForm"]["date1"].value;
		var radios = document.getElementsByName('carrier');

                for (var i = 0, length = radios.length; i < length; i++) {
                  if (radios[i].checked) {
                      company = radios[i].value;
                      break;
                      }
                }

		if (!isValidDate(date1)) {
			alert('Invalid date. Please enter a valid one.');
			message('Invalid data. Please try again.')
			return false;
		};
		if (!isValidZIP(zipcode1) || !isValidZIP(zipcode1)){
			alert('Invalid ZIP code. Please enter a valid one.');
			message('Invalid data. Please try again.')
			return false;
		};
		if (!isNumber(weight)) {
			alert('Invalid weight. Please enter a valid one.');
			message('Invalid data. Please try again.')
			return false;
		}
                else if (company=='UPS' && parseFloat(weight)>150){
                      alert('UPS ground only calculates <150 lbs');
                      message('Invalid data. Please try again.')
                      return false;
                       };
		
	}
	
	function validateNumber(evt) {
	  var theEvent = evt || window.event;
	  var key = theEvent.keyCode || theEvent.which;
	  key = String.fromCharCode( key );
	  var regex = /[0-9]|\.\b/;
	  if( !regex.test(key) ) {
	    theEvent.returnValue = false;
	    if(theEvent.preventDefault) theEvent.preventDefault();
	  }
	}
	
	function validateDate(evt) {
	  var theEvent = evt || window.event;
	  var key = theEvent.keyCode || theEvent.which;
	  key = String.fromCharCode( key );
	  var regex = /[0-9]|[\b-\/]/;
	  if( !regex.test(key) ) {
	    theEvent.returnValue = false;
	    if(theEvent.preventDefault) theEvent.preventDefault();
	  }
	}
	
	function validateZip(evt) {
	  var theEvent = evt || window.event;
	  var key = theEvent.keyCode || theEvent.which;
	  key = String.fromCharCode( key );
	  var regex = /[0-9]|[-\b]/;
	  if( !regex.test(key) ) {
	    theEvent.returnValue = false;
	    if(theEvent.preventDefault) theEvent.preventDefault();
	  }
	}
		
	function isValidDate(date)	{
	    var matches = /^(\d{2})[-\/](\d{2})[-\/](\d{4})$/.exec(date);
	    if (matches == null) return false;
	    var d = matches[2];
	    var m = matches[1] - 1;
	    var y = matches[3];
	    var composedDate = new Date(y, m, d);
	    return composedDate.getDate() == d &&
	            composedDate.getMonth() == m &&
	            composedDate.getFullYear() == y;
	}
		
	function isValidZIP(zip) {
	    var regex = /^\d{5}(-\d{4})?(?!-)$/;
	    if (zip.match(regex)) return true;
	    return false;
		}
	
	
</script>

<body onload="inputDate()">
<div class="container">
<h4 id="message" class="instructions">{{info}}</h4>
{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}


<form action="{% url 'shipping:index' %}" method="post" class="inputForm" name="shippingForm" onsubmit="return validateForm();" >
	{% csrf_token %}
	<h4 class="subtitle">Shipping Calculator:</h4>
	<div class="button_container">
	<input type="button" class="button" value="Clear All" title="Clear the contents of the input box." onclick="clearBox()"/>
	</div>
	<div class="inputsContainer">
	<label class="label_input">ZIP sender:</label>
	<input class="inputclass" name="zipcode1" id="zipcode1" value="{{zipcode1}}" onkeypress='validateZip(event)' />
	<div class="button_container">
		<select class="warehouse_select" id="input_warehouse" onchange="warehouse(this)">
			<option value="MRO warehouse" selected="selected">MRO warehouse</option>
			<option value="ACtech">ACtech</option>
			<option value="Dodge">Dodge Cross</option>
			<option value="Grove WI">Grove WI</option>
			<option value="IDC IN">IDC IN</option>
			<option value="Redlion">Redlion</option>
			<option value="Boston NC">Boston NC</option>
			<option value="Boston NV">Boston NV</option>
			<option value="IPTCI MN">IPTCI MN</option>
			<option value="MAGPOWR">MAGPOWR</option>
		</select>
	</div>
	<label class="label_input">ZIP destination:</label>
	<input class="inputclass" name="zipcode2" id="zipcode2" value="{{zipcode2}}" onkeypress='validateZip(event)' />
	<label class="label_input">Weight (lbs):</label>
	<input class="inputclass" name="weight" id="weight" value="{{weight}}" onkeypress='validateNumber(event)' />
	<label class="label_input">Date departure:</label>
	<input class="inputclass" name="date1" id="date1" value="{{date1}}" onkeypress='validateDate(event)'/>
	<div class="button_container">
	<label class="label_radio">UPS</label>
	<input type="radio" class="radio" value="UPS" name="carrier" id="UPS" checked="checked" />
	</div>
	</div>
	<div class="button_container">
	<input type="submit" class="button" value="Search" title="Search the selected supplier." onclick="message('Working... Please wait a minute.')"/>
	</div>
</form>

<div class="resultTable">
	{{ results|safe }}
</div>
</div>
</body>

shipping/templates/shipping/index_backup.html
<head>
	<title>Shipping Cost Calculator</title>
	<link rel="stylesheet" type="text/css" href="{{ STATIC_URL }}shipping/style.css">
	
</head>
<script>
	function message(message){
		document.getElementById('message').innerHTML = message;
	}
	
	function clearBox(){
		document.getElementById("zipcode1").value = '';
		document.getElementById("zipcode2").value = '';
		document.getElementById("weight").value = '';
	}
	
	function focusInBox(){
		var today = new Date();
		var dd = today.getDate();
		var mm = today.getMonth()+1; //January is 0!
		var yyyy = today.getFullYear();
		if(dd<10){dd='0'+dd} {if(mm<10){mm='0'+mm} today = mm+'/'+dd+'/'+yyyy;}
		var box = document.getElementById("date1");
		if (box.value==today) {
			box.value = '';
		}
	}

	function focusOutBox(){
		var today = new Date();
		var dd = today.getDate();
		var mm = today.getMonth()+1; //January is 0!
		var yyyy = today.getFullYear();
		if(dd<10){dd='0'+dd} {if(mm<10){mm='0'+mm} today = mm+'/'+dd+'/'+yyyy;}
		var box = document.getElementById("date1");
		if (box.value=="") {
			box.value = today;
		}
	}
		
	function warrehouse(obj) {
     if(obj.checked) {
         document.getElementById("zipcode1").value = '90023'
     }
     else {
     	document.getElementById("zipcode1").value = ''
     }
	}
	
	function inputDate(){
		var today = new Date();
		var dd = today.getDate();
		var mm = today.getMonth()+1; //January is 0!
		
		var yyyy = today.getFullYear();
		if(dd<10){dd='0'+dd} {if(mm<10){mm='0'+mm} today = mm+'/'+dd+'/'+yyyy;}
		document.getElementById("date1").value = today;
	}
	
	function isNumber(n) {
	  return !isNaN(parseFloat(n)) && isFinite(n);
	}
	
	function validateForm(){
		var zipcode1=document.forms["shippingForm"]["zipcode1"].value;
		var zipcode2=document.forms["shippingForm"]["zipcode2"].value;
		var weight=document.forms["shippingForm"]["weight"].value;
		var date1=document.forms["shippingForm"]["date1"].value;
		var radios = document.getElementsByName('carrier');

                for (var i = 0, length = radios.length; i < length; i++) {
                  if (radios[i].checked) {
                      company = radios[i].value;
                      break;
                      }
                }

		if (!isValidDate(date1)) {
			alert('Invalid date. Please enter a valid one.');
			message('Invalid data. Please try again.')
			return false;
		};
		if (!isValidZIP(zipcode1) || !isValidZIP(zipcode1)){
			alert('Invalid ZIP code. Please enter a valid one.');
			message('Invalid data. Please try again.')
			return false;
		};
		if (!isNumber(weight)) {
			alert('Invalid weight. Please enter a valid one.');
			message('Invalid data. Please try again.')
			return false;
		}
                else if (company=='UPS' && parseFloat(weight)>150){
                      alert('UPS ground only calculates <150 lbs');
                      message('Invalid data. Please try again.')
                      return false;
                       };
		
	}
	
	function validateNumber(evt) {
	  var theEvent = evt || window.event;
	  var key = theEvent.keyCode || theEvent.which;
	  key = String.fromCharCode( key );
	  var regex = /[0-9]|\.\b/;
	  if( !regex.test(key) ) {
	    theEvent.returnValue = false;
	    if(theEvent.preventDefault) theEvent.preventDefault();
	  }
	}
	
	function validateDate(evt) {
	  var theEvent = evt || window.event;
	  var key = theEvent.keyCode || theEvent.which;
	  key = String.fromCharCode( key );
	  var regex = /[0-9]|[\b-\/]/;
	  if( !regex.test(key) ) {
	    theEvent.returnValue = false;
	    if(theEvent.preventDefault) theEvent.preventDefault();
	  }
	}
	
	function validateZip(evt) {
	  var theEvent = evt || window.event;
	  var key = theEvent.keyCode || theEvent.which;
	  key = String.fromCharCode( key );
	  var regex = /[0-9]|[-\b]/;
	  if( !regex.test(key) ) {
	    theEvent.returnValue = false;
	    if(theEvent.preventDefault) theEvent.preventDefault();
	  }
	}
		
	function isValidDate(date)	{
	    var matches = /^(\d{2})[-\/](\d{2})[-\/](\d{4})$/.exec(date);
	    if (matches == null) return false;
	    var d = matches[2];
	    var m = matches[1] - 1;
	    var y = matches[3];
	    var composedDate = new Date(y, m, d);
	    return composedDate.getDate() == d &&
	            composedDate.getMonth() == m &&
	            composedDate.getFullYear() == y;
	}
		
	function isValidZIP(zip) {
	    var regex = /^\d{5}(-\d{4})?(?!-)$/;
	    if (zip.match(regex)) return true;
	    return false;
		}
	
	
</script>

<body onload="inputDate()">
<div class="container">
<h4 id="message" class="instructions">{{info}}</h4>
{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}


<form action="{% url 'shipping:index' %}" method="post" class="inputForm" name="shippingForm" onsubmit="return validateForm();" >
	{% csrf_token %}
	<h4 class="subtitle">Shipping Calculator:</h4>
	<div class="button_container">
	<input type="button" class="button" value="Clear All" title="Clear the contents of the input box." onclick="clearBox()"/>
	</div>
	<div class="inputsContainer">
	<label class="label_input">ZIP sender:</label>
	<input class="inputclass" name="zipcode1" id="zipcode1" value="{{zipcode1}}" onkeypress='validateZip(event)' />
	<div class="button_container">
	<label class="label_checkbox">MRO warehouse</label>
	<input class="checkbox" type="checkbox" value="our_warehouse" id="input_warehouse" onclick="warrehouse(this)" />
	</div>
	<label class="label_input">ZIP destination:</label>
	<input class="inputclass" name="zipcode2" id="zipcode2" value="{{zipcode2}}" onkeypress='validateZip(event)' />
	<label class="label_input">Weight (lbs):</label>
	<input class="inputclass" name="weight" id="weight" value="{{weight}}" onkeypress='validateNumber(event)' />
	<label class="label_input">Date departure:</label>
	<input class="inputclass" name="date1" id="date1" value="{{date1}}" onkeypress='validateDate(event)'/>
	<div class="button_container">
	<label class="label_radio">IDC-USA</label>
	<input type="radio" class="radio" value="IDC" name="carrier" id="IDC" />	
	<label class="label_radio">UPS</label>
	<input type="radio" class="radio" value="UPS" name="carrier" id="UPS" checked="checked" />
	</div>
	</div>
	<div class="button_container">
	<input type="submit" class="button" value="Search" title="Search the selected supplier." onclick="message('Working... Please wait a minute.')"/>
	</div>
</form>

<div class="resultTable">
	{{ results|safe }}
</div>
</div>
</body>

shipping/templates/shipping/search.html
<head>
<title>Tracking Numbers</title>
<link rel="stylesheet" type="text/css" href="{{ STATIC_URL }}tracking/style.css">
</head>

<body>
<div class="container">	
<h3 class="instructions">These are the tracking numbers from {{ company }} </h3>
<textarea class="textArea" rows="25" cols="20" readonly="readonly">{{ codes }}</textarea>
<textarea class="textArea" rows="25" cols="20" readonly="readonly">{{ tracking }}</textarea>

{% if latest_numbers %}
    <ul>
    {% for shipping in latest_numbers %}
        <li><a href="/tracking/{{ shipping.orderNumber }}/">{{ shipping.trackNumber }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No recent order numbers were introduced.</p>
{% endif %}

</div>

</body>